baseURL: http://example.org/
disablePathToLower: true
defaultContentLanguage: en
languageCode: en
title: Radifar
theme: PaperMod

googleAnalytics: G-3W7CK0FKYT

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

disqusShortname: radifar-github-io